#!/system/bin/sh

if [ "$1" == "rw" ]; then
mount -o remount,rw /dev/block/mmcblk0p15 /system
elif [ "$1" == "ro" ]; then
mount -o remount,ro /dev/block/mmcblk0p15 /system
else
echo "Usage: mntsys { rw | ro } mount system rw or ro"

fi
